In [2]:
import numpy as np

### 1. Create Numpy Array

In [24]:
# Create numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1), arr1.dtype, arr1.shape)  # 1-D array

arr2 = np.array([1,2,3,4,5,"aman"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)  # Unicode array

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)  # 2-D array

arr4 = np.zeros((2,3))
print(arr4, type(arr4), arr4.dtype, arr4.shape)  # Zero array

arr5 = np.ones((2,3), dtype="int32")
print(arr5, type(arr5), arr5.dtype, arr5.shape)  # Ones array

arr6 = np.full((2,3), 100)
print(arr6, type(arr6), arr6.dtype, arr6.shape)  # Full array

arr7 = np.eye(3)
print(arr7, type(arr7), arr7.dtype, arr7.shape)  # Identity array

arr8 = np.arange(1,11,2)
print(arr8, type(arr8), arr8.dtype, arr8.shape)  # Range elements

arr9 = np.linspace(0, 100, 5)
print(arr9, type(arr9), arr9.dtype, arr9.shape)  # Evenly spaced

arr10 = np.array([3 + 5j])
print(arr10, type(arr10), arr10.dtype, arr10.shape)  # Complex no. (dtype = real + imaginary)

arr11 = np.array(["prime", {1,2,3}, 3.14])
print(arr11, type(arr11), arr11.dtype, arr11.shape)  # Heterogeneous - object

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'aman'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> int64 (2, 3)
[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> float64 (2, 3)
[[1 1 1]
 [1 1 1]] <class 'numpy.ndarray'> int32 (2, 3)
[[100 100 100]
 [100 100 100]] <class 'numpy.ndarray'> int64 (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'> float64 (3, 3)
[1 3 5 7 9] <class 'numpy.ndarray'> int64 (5,)
[  0.  25.  50.  75. 100.] <class 'numpy.ndarray'> float64 (5,)
[3.+5.j] <class 'numpy.ndarray'> complex128 (1,)
['prime' {1, 2, 3} 3.14] <class 'numpy.ndarray'> object (3,)


### 2. Properties

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)  # shape (m,n)
print(arr.size)   # total element
print(arr.dtype)  # datatype
print(arr.ndim)   # dimensions

float_arr = arr.astype(np.float64)  # Type conversion
print(float_arr, float_arr.dtype)

(2, 3)
6
int64
2
[[1. 2. 3.]
 [4. 5. 6.]] float64


### 3. Operations

In [9]:
# Reshaping array
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3,2))
print(reshaped_arr, reshaped_arr.shape)

flattened_arr = arr.flatten()
print(flattened_arr, flattened_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [16]:
# Indexing
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0][1]) # normal indexing

arr = np.array([1,2,3,4,5])
idx = [0,2,4]
print(arr[idx])  # fancy indexing

print(arr[arr%2 == 0])  # boolean indexing

2
[1 3 5]
[2 4]


In [19]:
# Slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4:2])  # [start, end, step]

# Note: In python list-slicing creates copy, In numpy arr-slicing creates view
sliced_arr = arr[1:4:2].copy()  # to create copy

[2 4]


### 4. Axes
- 1D -> 1axes (row)
- 2D -> 2axes (rows, columns)
- 3D -> 3axes (depth, row, column)

In [30]:
# 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("Sum of all elements: ",np.sum(arr))

col_sum = np.sum(arr, axis=0)
print("Sum of all columns: ", col_sum)

row_sum = np.sum(arr, axis=1)
print("Sum of all rows: ", row_sum)

[[1 2 3]
 [4 5 6]]
Sum of all elements:  21
Sum of all columns:  [5 7 9]
Sum of all rows:  [ 6 15]


In [34]:
# 3-D array
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr, arr.shape)

print(arr[0,1,0])  # indexing
print(arr[:,0,:])  # slicing

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
3
[[1 2]
 [5 6]]


### 5. Vectorization & Broadcasting

In [37]:
# Vectorization
arr1 = np.array([0,1,2,3,4])
arr2 = np.array([5,6,7,8,9])

print("Square: ", arr1 ** 2)
print("Sum: ", arr1 + arr2)

Square:  [ 0  1  4  9 16]
Sum:  [ 5  7  9 11 13]


In [40]:
# Broadcasting (scaling)
# rule - both have equal shape, or one of them is 1
arr1 = np.array([0,1,2,3,4])
arr2 = np.array([[0,1,2,3,4], [5,6,7,8,9]])

print(arr1 + arr2)
print(arr1.shape, arr2.shape) # 5 is matching

[[ 0  2  4  6  8]
 [ 5  7  9 11 13]]
(5,) (2, 5)


### 6. Normalization

In [45]:
# 1. Std. Normalization (z-score) {(arr-mean)/std. dev}
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
print("Mean: ", mean)
std_dev = np.std(arr)
print("Std. Dev: ", std_dev)

normalized_arr = (arr-mean)/std_dev  # mean will be 0
print(normalized_arr, np.mean(normalized_arr))

Mean:  2.5
Std. Dev:  1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]] 0.0


### 7. Mathematical Functions

In [50]:
# Aggregation
arr = np.array([1,2,3,4,5])

print(np.sum(arr))    # sum
print(np.prod(arr))   # product
print(np.min(arr))    # min value
print(np.max(arr))    # max value
print(np.argmin(arr)) # min value index
print(np.argmax(arr)) # max value index
print(np.mean(arr))   # mean
print(np.std(arr))    # std. deviation
print(np.median(arr)) # median
print(np.var(arr))    # variance

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
